name: Basic Push

on:
    push:
        branches:
          - 'main'
        paths-ignore:
          - '**.md' 
jobs:

    Push_detected:
        runs-on: ubuntu-latest
        steps:
          -  name: Push Detected
             run: echo "Push detected!"