name: Basic Push

on:
    push:
        branches:
          - 'main'
        paths:
          - 'src/**' 


jobs:

    Push_detected:
        runs-on: ubuntu-latest
        steps:
          -  name: Push Detected
             run: echo "Push detected!"