name: First_Example

on:
    push:

jobs:
    First_job:
        runs-on: ubuntu-latest
        steps:
            - name: CheckOut
              uses: actions/checkout@v6
              
            - name: List and Read
              run: |
                echo "My FirstName GitHub Actions job"
                ls -la
                cat README.md

            
            - name: Generet Drow Digital
              run: cowsay -f dragon "Run for conver, I am DRAGON...RAWR" >> dragon.txt
            
            # - name: Read Read.md
            #   run: 