name: Generate ASCII ArtWork

on:
    push:

jobs:
    ascii_job:
        runs-on: ubuntu-latest
        steps:
          - name: Repo CheckOut
            uses: actions/checkout@v6

          - name: Checkout Repo lsit
            run: ls

          - name: Runs_Shell With Permission 
            run: | 
             chmod +x script_ascii.sh
              ./script_ascii.sh

          
            
