name: Generate ASCII ArtWork

on:
    push:

jobs:
    Build_job_1:
        runs-on: ubuntu-latest
        steps:
          - name: Install Cowsay program
            run: sudo apt-get install cowsay -y

          - name: Execute Cowsay job
            run: cowsay -f dragon "Run for conver, I am DRAGON...RAWR" >> dragon.txt

          - name: sleep for 30 secound
            run: sleep 30

    Test_job_2:
          runs-on: ubuntu-latest
          needs: 
            - Build_job_1
          steps:
            - name: sleep for 10 secound
              run: sleep 10

            - name: Test Find File
              run: grep -i "dragon" dragon.txt

    Deploy_Job_3:
        runs-on: ubuntu-latest
        needs: 
            - Test_job_2
        steps:
            - name: Read File
              run: cat dragon.txt

            - name: Deploy
              run: echo "Deploying... ..."

         

          
            
