name: Hybrid Pipline
on:
  push:
    branches:
      - 'main'
    paths:
      - 'src/**'
      - 'src/**.md'
  workflow_dispatch:
    inputs:
      event_target:
        description: Choice env
        type: choice
        options:
          - 'staging'
          - 'production'
        default: "staging"
      user_token:
         description: user enter password
         type: string
         required: true
        
jobs:
  test_job:
    runs-on: ubuntu-latest
    steps:
      - name: Run Test Job
        run: echo "job run"

  Check_Paasword:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    needs: 
      - test_job
    env:
      Paasword: ${{secrets.RUN_PASSWORD}}
    steps:
      - name: check Password
        if: github.event.inputs.user_token != env.Paasword
        run: echo "your Token not correct !!" && exit 1

  Job_deploy:
    runs-on: ubuntu-latest
    needs: [test_job, Check_Paasword]
    if: github.event_name == 'workflow_dispatch'
    steps:
      - name: deploy_job
        if: github.ref != 'refs/heads/main' 
        run: |
          echo "You are trying to deploy the on different branch: " ${{github.ref}}
          echo "Only allow main branch deploy !"
          exit 1
      - name: deploy_job
        run: |
          echo "The evn you are: " ${{github.event.inputs.event_target}}
        

