name: Matrix Configuration 

on:
  push:
  workflow_dispatch:

jobs:
    deploy:
        strategy:
          matrix:
            os: [ubuntu-latest , windows-latest ,ubuntu-20.04 ]
            images: [hello-world, alpine]
        runs-on: ${{matrix.os}}
        steps:
          - name: Echo Docker info
            run: docker info
          
          - name: Run Image on ${{matrix.os}}
            run: docker run ${{matrix.images}}
    