name: pr-check

on: 
    pull_request:
        branches:
            - 'main'        

jobs:
    review-code:
      runs-on: ubuntu-latest
      steps:
        - name: Run Test Job
          run: echo "Checking the new code... Wait!"


