name: workflow-dispatch

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'env choice'
        default: "staging"
        required: true
        type: choice
        options:
            - staging
            - production
      run_tests:
        description: 'Run tests before deploy?'
        required: true
        type: boolean
        default: true
jobs:
    job1:
      name: Unit Testing
      runs-on:
        - ubuntu-latest
      steps:
        - name: Deploy to Staging
          if: github.event.inputs.environment == 'staging'
          run: echo "Deploying to Staging environment..."

        - name: Deploy to production
          if: github.event.inputs.environment == 'production'
          run: echo  "WARNING:Deploying to PRODUCTION!"

        - name: Run unit tests
          if: github.event.inputs.run_tests == true
          run: echo "Running tests..."
