name: Workflow Filters And Activities 

on:
    workflow_dispatch:
    
    push:
      branches: 
        - main
        - '!featcher/*'
    pull_request:
      types:
        - opened
        - closed
      branches: 
        - main
jobs:
    hello:
        runs-on: ubuntu-latest
        steps:
          - run: echo this workflow/job/step/ is executed for event type - ${{github.event_name}}  