name: WorkFlow_Secret

on:
    workflow_dispatch:
        inputs:
            user_token: 
                description: 'Enter Password:'
                type: string
                required: true
jobs:
    secure-job:
        runs-on: ubuntu-latest
        env:
          PASSWORD_FROM_SECRET: ${{ secrets.RUN_PASSWORD }}
        steps:
          - name: Print Massage
            run: echo "Hello we will Checking token"

          - name: Run critical task
            if: github.event.inputs.user_token == env.PASSWORD_FROM_SECRET
            run: echo "Token is correct! Running the secret task"

          - name: Show error message Password
            if: github.event.inputs.user_token != env.PASSWORD_FROM_SECRET
            run: |
              exit 1
              echo "WRONG TOKEN! Access denied"
              
            

